version: '3.8'
services:
  app:
    build: .
    image: mycustomblog:latest  # Custom image name and tag
    ports:
      - "3001:3001"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    expose:
      - "6379"
